Fixed label positions
vergauwenthomas/MetObs_toolkit pull request #185
Opened 2023-05-16 15:41 UTC by ACovaci99

2023-05-16 15:44 UTC, ACovaci99 commented
Ready for review

2023-05-17 07:16 UTC, vergauwenthomas requested changes

2023-05-17 07:16 UTC, vergauwenthomas commented on development/launch_gui.ipynb
@ACovaci99 remove this file from the commit.

2023-05-17 07:16 UTC, vergauwenthomas commented on examples/plotting_example.py
> +sys.path.append(str(main_folder))
comment these lines (these should only be uncommented by developers, and not in the repo)

2023-05-17 07:16 UTC, vergauwenthomas commented on examples/plotting_example.py
> +    output_folder="C:/Users/andre/Desktop/test/",
`output_folder="/home/$USER/output/"`

2023-05-17 07:16 UTC, vergauwenthomas commented on examples/plotting_example.py
> +                           startdt=None, enddt=None, plot=True, colorby='name', errorbands=False, verbose=False)
Remove these lines. There will be a seperate example on diurnal analysis.

2023-05-17 14:26 UTC, vergauwenthomas commented
@ACovaci99 I will fixe the review so i can deploy a new version

2023-05-17 14:34 UTC, vergauwenthomas commented
resolved in #191

2023-05-17 14:34 UTC, closed without merging